name: tracer_study
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_core: ^2.4.0
  google_fonts: ^3.0.1
  firebase_auth: 4.2.1
  cloud_firestore: 4.2.0
  firebase_storage: 11.0.8
  svg_icon: ^0.0.1
  image_picker: 0.8.6
  path_provider: ^2.0.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
