// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyDnXgn7DuPowOfzjuDW-6vMAesWylL1zzA',
    appId: '1:325370593159:android:32a6db1f3dee7d5d421d22',
    messagingSenderId: '325370593159',
    projectId: 'tracer-study-8c1a7',
    storageBucket: 'tracer-study-8c1a7.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyBH29sbpZMHcQnpFcHNwtkd7-ClPgzkCBY',
    appId: '1:325370593159:ios:07933252dbbeafef421d22',
    messagingSenderId: '325370593159',
    projectId: 'tracer-study-8c1a7',
    storageBucket: 'tracer-study-8c1a7.appspot.com',
    iosClientId:
        '325370593159-mggbcle2d9olfve39eg6qk9ph0flpb24.apps.googleusercontent.com',
    iosBundleId: 'com.example.tracerStudy',
  );
}
